CC = g++
CFLAGS = -pedantic -Wall -Werror -Wno-sign-compare -Wno-long-long -lm -O2
FILES = main.cpp TString.cpp TString.h BTree.h BTree.cpp 
PROG = da2

all:
	$(CC) $(CFLAGS) -o $(PROG) $(FILES)
